# Generated by Django 5.2 on 2026-01-14 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('customer_number', models.CharField(blank=True, max_length=20, verbose_name='Número de Cliente')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de orden')),
                ('device_type', models.CharField(choices=[('phone', 'Celular'), ('tablet', 'Tablet'), ('laptop', 'Notebook'), ('desktop', 'PC de Escritorio'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de dispositivo')),
                ('device_brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('device_model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('device_color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('device_serial', models.CharField(blank=True, max_length=100, verbose_name='Serial/IMEI')),
                ('security_data', models.TextField(blank=True, help_text='Clave, patrón, PIN, etc.', verbose_name='Datos de Seguridad')),
                ('problem_description', models.TextField(verbose_name='Descripción del problema')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('repair_notes', models.TextField(blank=True, verbose_name='Notas de reparación')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('in_service', 'En Servicio'), ('repaired', 'Reparado'), ('not_repaired', 'No Reparado'), ('not_solved', 'No Solucionado'), ('ready', 'Listo para Entrega'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='received', max_length=20, verbose_name='Estado')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo estimado')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo final')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adelanto/Seña')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('not_paid', 'Sin Abonar')], default='not_paid', max_length=20, verbose_name='Método de Pago')),
                ('general_observations', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('received_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Entrega estimada')),
                ('delivered_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden de reparación',
                'verbose_name_plural': 'Órdenes de reparación',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nuevo estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.repairorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-created_at'],
            },
        ),
    ]
