# Generated by Django 5.0.1 on 2026-02-24 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_supplier'),
        ('orders', '0003_add_parts_cost_to_repairorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='orders.repairorder', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_orders', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Repuesto de orden',
                'verbose_name_plural': 'Repuestos de orden',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
