# Generated by Django 5.0 on 2026-03-18 03:13

from django.db import migrations


def fix_payment_status(apps, schema_editor):
    """
    Recalcula el payment_status y balance de todas las órdenes existentes
    según la nueva lógica implementada en el modelo.
    """
    RepairOrder = apps.get_model('orders', 'RepairOrder')

    for order in RepairOrder.objects.all():
        # Obtener el costo total (preferir final_cost, sino estimated_cost)
        total_cost = order.final_cost if order.final_cost else order.estimated_cost

        # Calcular balance y estado de pago según el método
        if order.payment_method == 'account':
            # Cuenta corriente - calcular saldo pendiente
            if total_cost:
                order.balance = total_cost - order.paid_amount

                # Actualizar estado de pago
                if order.balance <= 0:
                    order.payment_status = 'paid'
                    order.balance = 0
                elif order.paid_amount > 0:
                    order.payment_status = 'partial'
                else:
                    order.payment_status = 'pending'

        elif order.payment_method == 'not_paid':
            # Sin abonar - calcular balance basado en adelanto/seña
            if order.deposit_amount > 0:
                order.paid_amount = order.deposit_amount
                if total_cost:
                    order.balance = total_cost - order.paid_amount

                    # Actualizar estado
                    if order.balance <= 0:
                        order.payment_status = 'paid'
                        order.balance = 0
                    else:
                        order.payment_status = 'partial'
            else:
                # Sin adelanto - todo pendiente
                order.paid_amount = 0
                order.balance = total_cost if total_cost else 0
                order.payment_status = 'pending'

        else:
            # Efectivo, Transferencia - considerado como pagado
            if total_cost:
                order.paid_amount = total_cost
            order.balance = 0
            order.payment_status = 'paid'

        order.save(update_fields=['payment_status', 'balance', 'paid_amount'])


def reverse_fix(apps, schema_editor):
    """
    No hacemos nada en el reverso, ya que no podemos saber
    cuál era el estado anterior incorrecto.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_order_parts'),
    ]

    operations = [
        migrations.RunPython(fix_payment_status, reverse_fix),
    ]
