# Generated by Django 5.2 on 2026-01-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('device_brand', models.CharField(blank=True, max_length=100, verbose_name='Marca del Equipo')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='Modelo del Equipo')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('estimated_time', models.CharField(blank=True, help_text='Ej: 2-3 días', max_length=50, verbose_name='Tiempo Estimado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
    ]
