# Generated by Django 5.0 on 2026-01-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proveedor'),
        ),
    ]
